version: '2.2'
services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes: 
       - ./prometheus:/etc/prometheus
    command: "--config.file=/etc/prometheus/prometheus.yaml --storage.tsdb.retention.time=10m"
    ports: 
      - 9090:9090      
    restart: "no"
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter    
    ports:
      - 9100:9100      
    restart: "no"    

networks:  
  default:
    external:
      name: prom_net

